<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{

  /**
  *  @param \Datetime $date
  *  @return integer
  **/
  public function countHowManyDailyTicket(\Datetime $date)
  {

    $query = $this->createQueryBuilder('b')
        ->select('COUNT(t)') // revoir cours doctrine COUNT
        ->where('b.visitDate = :visitDate')
        ->setParameter('visitDate', $date)
        ->innerJoin('b.tickets','t')
        ->getQuery();

    return $query->getSingleScalarResult();

  }
}
